version: 0.2

phases:
  pre_build:
    commands:
      - echo "Aggressive cleaning of workspace..."
      - rm -rf *
      - rm -rf .next
      - rm -rf .git
      - git clone $CODEBUILD_SOURCE_REPO_URL .
      - git checkout $CODEBUILD_SOURCE_VERSION
      - echo "Listing all files in directory..."
      - ls -la
      - echo "Checking for db.ts..."
      - find . -name "db.ts" || echo "db.ts not found"
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Next.js application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - echo "Final directory contents:"
      - ls -la

artifacts:
  files:
    - '**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'post-deploy.sh'
    - '.next/**/*'
    - 'public/**/*'
  base-directory: '.'
  discard-paths: no
